### ISSUE TITLE
Do we need to reimplement `sequence` or `type-aligned` dependencies for performance reasons?

### ISSUE THREAD

**Issue by dagit** [dagit/logict-sequence#4]
Currently we use the versions of `sequence` and `type-aligned` available on hackage but I don't think the author is very active. I think constant factor performance of `SeqT` will be largely dictated by the performance of those libraries. Would it make sense to incorporate them directly into this package so we can optimize them directly for our use cases?

@treeowl Do you have any thoughts on this?

**Comment by treeowl** [comment]
I dug into it some more. As far as I can tell, this particular application doesn't *need* type-aligned queues at all. So we should be able to use whatever queues we want, and drop the `AsUnitLoop` stuff altogether. Sheesh. Question: do we want concatenation to be lazy in the second argument? It currently isn't, and I don't know if that matters.

**Comment by dagit** [comment]
If you could make a toy version without type-aligned sequences that would be interesting. I wonder if `Data.Sequence` would be a good choice in that case?

I'm not sure about the lazy second argument. I'd have to make some examples where the strictness difference matters and some benchmarks. I wonder if this ends up being like `StatT` where you want to provide both a lazy and strict variant.

**Comment by treeowl** [comment]
`Data.Sequence` is overkill for two reasons.

1. It includes size annotations in the nodes to support `lookup` and `splitAt`, neither of which are of any use whatsoever here.
2. It supports all four deque operations; supporting only the ones we need should make some operations faster and/or make them use less code.

**Comment by treeowl** [comment]
Looking at `FastQueue` and `ToCatQueue`, I see one area where we could probably improve matters pretty easily.

```haskell
data FastQueue tc a b where
  RQ :: !(ConsList tc a b) -> !(SnocList tc b c) -> !(ConsList tc x b) -> FastQueue tc a c

data ToCatQueue q c x y where
  C0 :: ToCatQueue q c x x
  CN :: c x y -> !(q (ToCatQueue q c) y z) -> ToCatQueue q c x z
```

The `q` in `ToCatQueue` is `FastQueue`. We'd almost certainly be better off unpacking `FastQueue` into `ToCatQueue`. This of course means baking `FastQueue` into `ToCatQueue`. Additionally, because GHC *still* doesn't know how to unpack existentials, we'll want to drop the existential from `FastQueue`, and accept the (quite minor) loss of the safety it provides. If we're going to all this trouble, we may well want to drop the whole type-alignment thing while we're at it.

**Comment by treeowl** [comment]
Such a modified version of this catenable queue should be benchmarked against something more similar to `Data.Sequence`. The latter has worse asymptotics, but not by a lot (concatenation is logarithmic in the length of the shorter queue rather than constant), and the constant factors might well be better.

**Comment by treeowl** [comment]
It turns out that the original `reflectionwithoutremorse` implementation is *wrong*, and so was the implementation here that was based on it. It seems we really *need* a peculiarly lazy queue. The doesn't seem to be any way around that without sometimes forcing computations on the right of a `<|>` too early. *Conceptually*, what we want is a lazy, catenable, *non-empty* queue. What's currently in `main` is instead a lazy, catenable queue with slightly broken amortized bounds (due to the risk of appended `Empty`s). We *could* use a nonempty version, representing the failing logic computation as `empty = SeqT (pure Empty)`. Should we? I don't know; I can open an issue to investigate. That would be simpler/cleaner in some ways but would be (probably only slightly) less efficient in something like `(if b then ... else empty) <|> m`.
